### PR TITLE
Fix encoding error in utils.py

### PR DESCRIPTION
**Pull request by JohnZ03**
Non-ASCII colon sign being used and causing error on local deployment during every localhost startup.

### 描述
描述您的 pull request 所做的更改。
另外请附上相关程序运行时的截图（before & after），以直观地展现您的更改达成的效果。

### 相关问题
（如有）请列出与此拉取请求相关的issue。

### 补充信息
（如有）请提供任何其他信息或说明，有助于其他贡献者理解您的更改。
如果您提交的是 draft pull request，也请在这里写明开发进度。

### Summary
🕒🖥️🐛

Fixed a bug in `modules/utils.py` that prevented saving files on Windows due to an invalid character in the datetime format. This resolved issue #1.

> _`datetime` format_
> _colon changed to avoid error_
> _a winter bug fixed_

### Walkthrough
* Fix datetime format string to use regular colon instead of unicode character ([link](https://github.com/GaiZhenbiao/ChuanhuChatGPT/pull/882/files?diff=unified&w=0#diff-875600658966e53900b1b063d3f37d175ba9f9fffee31acfce3f8de15b75df72L671-R671)). This prevents an error when saving the file name on Windows systems and resolves issue #1. The affected file is `modules/utils.py`.

### CODE REVIEW

**Comment by MZhao-ouo** [comment]
What platform do you use? I changed it to Non-ASCII because the normal colon is forbidden on Windows. We have tested it on Windows, macOS, and Linux, and everything is working fine.

**Comment by JohnZ03** [comment]
> What platform do you use? I changed it to Non-ASCII because the normal colon is forbidden on Windows. We have tested it on Windows, macOS, and Linux, and everything is working fine.

I'm using Win 11 Pro English version. I'll reproduce the error message and show you.

**Comment by MZhao-ouo** [comment]
> > What platform do you use? I changed it to Non-ASCII because the normal colon is forbidden on Windows. We have tested it on Windows, macOS, and Linux, and everything is working fine.
> 
> I'm using Win 11 Pro English version. I'll reproduce the error message and show you.

Sounds like Chinese version Windows is OK. We will replace it by `-`.
Thanks!

**Comment by GaiZhenbiao** [comment]
I understand. This error occurs because Windows doesn't use utf-8 encoding as default. So I changed the colon to a dash.

**Comment by Keldos-Li** [comment]
If you submit an issue first, we can discuss it in detail. But I find the support of different system languages for Unicode a really interesting topic.

**Pull request merged**
