### PR TITLE
增加对文心一言的支持，支持文心一言的三个主要模型。

### PR DESCRIPTION
**Pull request by XudongLiu**
### 描述
增加了对百度文心一言模型的支持，主要支持百度三个主要模型ERNIE-Bot、ERNIE-Bot-4、ERNIE-Bot-Tubor
截屏2023-11-08 15 09 16

### 相关问题
[功能请求]: 请问什么时候能够支持文心一言呢 #928

### 补充信息
无

### Summary
🗣️🌐🐼

This pull request adds support for using ERNIE, a pre-trained dialogue model from Baidu Cloud, as an online service for generating chat responses. It updates the base model class, the presets module, the config files, and the models module to handle the ERNIE model type and its parameters. It also adds a new module `ERNIE.py` that defines a class to interact with the ERNIE model service.

> _To chat with ERNIE online_
> _We need some keys to access its mind_
> _We read them from `config`_
> _Or env vars if we pick_
> _And use `ERNIE_Client` of a kind_

### Walkthrough
*  Add support for ERNIE dialogue model from Baidu Cloud as an online service ([link](https://github.com/GaiZhenbiao/ChuanhuChatGPT/pull/931/files?diff=unified&w=0#diff-14bcebbd2e61e96a87dd9c50755465566354a360b1085cd2ff7ddce3c4f1a1fdR18-R19), [link](https://github.com/GaiZhenbiao/ChuanhuChatGPT/pull/931/files?diff=unified&w=0#diff-b4ba4a3f84ff5c85c144b2b9c28c5046d1c692e91e8231e55931413f7f21f666R134-R138), [link](https://github.com/GaiZhenbiao/ChuanhuChatGPT/pull/931/files?diff=unified&w=0#diff-3ca0698dd4eab37da223f4972bcf159dcc951ce059737efc0663d44a1a214b06R151), [link](https://github.com/GaiZhenbiao/ChuanhuChatGPT/pull/931/files?diff=unified&w=0#diff-3ca0698dd4eab37da223f4972bcf159dcc951ce059737efc0663d44a1a214b06R192-R193), [link](https://github.com/GaiZhenbiao/ChuanhuChatGPT/pull/931/files?diff=unified&w=0#diff-6087086023d896b1980ead28bdca9fda0dd4c916a4d681bdb416029ba47e8a44R1-R96), [link](https://github.com/GaiZhenbiao/ChuanhuChatGPT/pull/931/files?diff=unified&w=0#diff-d1891fbe5981bc67a31d0b1aa8819ad6c4f88cd13a52eda5c74c318cb50889feR131-R133), [link](https://github.com/GaiZhenbiao/ChuanhuChatGPT/pull/931/files?diff=unified&w=0#diff-2dd7551ecfb886cb4c1d16aeaf528f71e7a90a5f317da67152b9f5e190ddfce6L77-R80), [link](https://github.com/GaiZhenbiao/ChuanhuChatGPT/pull/931/files?diff=unified&w=0#diff-2dd7551ecfb886cb4c1d16aeaf528f71e7a90a5f317da67152b9f5e190ddfce6R152-R163))
  - Add two new fields to `config_example.json` for ERNIE API key and secret key ([link](https://github.com/GaiZhenbiao/ChuanhuChatGPT/pull/931/files?diff=unified&w=0#diff-14bcebbd2e61e96a87dd9c50755465566354a360b1085cd2ff7ddce3c4f1a1fdR18-R19))
  - Read ERNIE keys from config file or environment variables in `modules/config.py` and set them as global variables ([link](https://github.com/GaiZhenbiao/ChuanhuChatGPT/pull/931/files?diff=unified&w=0#diff-b4ba4a3f84ff5c85c144b2b9c28c5046d1c692e91e8231e55931413f7f21f666R134-R138))
  - Add a new enum value ERNIE to the ModelType class in `modules/models/base_model.py` to represent the ERNIE model type ([link](https://github.com/GaiZhenbiao/ChuanhuChatGPT/pull/931/files?diff=unified&w=0#diff-3ca0698dd4eab37da223f4972bcf159dcc951ce059737efc0663d44a1a214b06R151))
  - Add a new condition to the get_type method of the ModelType class to check if the model name contains "ernie" and return the ERNIE model type ([link](https://github.com/GaiZhenbiao/ChuanhuChatGPT/pull/931/files?diff=unified&w=0#diff-3ca0698dd4eab37da223f4972bcf159dcc951ce059737efc0663d44a1a214b06R192-R193))
  - Add a new module `modules/models/ERNIE.py` that defines a class ERNIE_Client that inherits from the BaseLLMModel class and implements the methods to interact with the ERNIE model service ([link](https://github.com/GaiZhenbiao/ChuanhuChatGPT/pull/931/files?diff=unified&w=0#diff-6087086023d896b1980ead28bdca9fda0dd4c916a4d681bdb416029ba47e8a44R1-R96))
  - Add a new branch to the get_model function in `modules/models/models.py` that imports the ERNIE_Client class and creates an instance of it with the given model name and the ERNIE keys ([link](https://github.com/GaiZhenbiao/ChuanhuChatGPT/pull/931/files?diff=unified&w=0#diff-d1891fbe5981bc67a31d0b1aa8819ad6c4f88cd13a52eda5c74c318cb50889feR131-R133))
  - Add the three ERNIE model names to the ONLINE_MODELS list in `modules/presets.py` to check if a model is an online service or a local file ([link](https://github.com/GaiZhenbiao/ChuanhuChatGPT/pull/931/files?diff=unified&w=0#diff-2dd7551ecfb886cb4c1d16aeaf528f71e7a90a5f317da67152b9f5e190ddfce6L77-R80))
  - Add the metadata for the three ERNIE models to the MODEL_METADATA dictionary in `modules/presets.py` to store information such as the model name and the token limit for each model ([link](https://github.com/GaiZhenbiao/ChuanhuChatGPT/pull/931/files?diff=unified&w=0#diff-2dd7551ecfb886cb4c1d16aeaf528f71e7a90a5f317da67152b9f5e190ddfce6R152-R163))

### CODE REVIEW

**Comment by XudongLiu** [comment]
截屏2023-11-08 15 26 48
这个是正确的截图

**Comment by Keldos-Li** [comment]
我测试了一下，大部分情况没有问题，但是在切换对话之后好像往往不能得到最新的一组对话，尝试切换对话后继续对话往往会提示
```
ValueError: ('Unable to parse text', 'or_code":33***6,"error_msg":"the role of first message must be user","id":"as-5buh********"}')
```
或者
```
ValueError: ('Unable to parse text', 'or_code":33***6,"error_msg":"the length of messages must be an odd number","id":"as-tf7********"}')
```
或者长久不反应……这时的报错反馈在前端体验也不好。

我不太确定这是我们本身base model的history就有点小问题，还是百度模型的问题。唔。

**Comment by XudongLiu** [comment]
我看看后续调整一下，这个文心一言的接口要求基数的内容必须是user的问题，这个有点变态，我再调整一下吧。

**Comment by saisaizhou** [comment]
请问文心一言应该用哪个access_token呢？尝试了以下用百度飞桨平台AI studio提供的文心一言access_token会报错

**Comment by XudongLiu** [comment]
@saisaizhou 可以使用百度云那里提供的文心的服务，里面有一个生成access_token的地方

**Pull request merged**
